### ISSUE TITLE
Restore possibility to compile documentation

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/cpp-sc2#2]
Use GitHub pages to host the API docs as Blizzard usually did. The docs should be published at the end of successful Travis CI build.

**Comment by alkurbatov** [comment]
Initial version was published. No Travis support so far.

**Comment by yanntm** [comment]
yay for PR https://github.com/alkurbatov/cpp-sc2/pull/31 letting us close this one 👍

**Comment by alkurbatov** [comment]
Implemented in #35. Need to set the token properly (if there is nothing set yet).

**Comment by alkurbatov** [comment]
>Need to set the token properly

Done, lets assume it is fixed. Further checks will be done on next minor release.
