### ISSUE TITLE
BattleCruiser weapons data is incorrect

### ISSUE THREAD

**Issue by mboedigh** [alkurbatov/cpp-sc2#26]
The weapon's data for Battlecruiser is empty (the vector that should contain the weapon's information is empty). To reproduce the error, add this code to OnGameStart(), or OnStep() (and #include <iostream>)

```
            auto& data = Observation()->GetUnitTypeData();
            auto& bc_data = data[(int)sc2::UNIT_TYPEID::TERRAN_BATTLECRUISER];
            auto& bc_weapons = bc_data.weapons;
            std::cout << bc_weapons.size() << std::endl;
```

Weapons data for other units, like Marine and Thor seem to be correct. Can anyone else reproduce this? I got a new computer and things just aren't working like they used to, but I don't know where it is broken.

**Comment by RaphaelRoyerRivard** [comment]
But this isn't related to the API, so not sure if it fits here.

**Comment by mboedigh** [comment]
I didn't know it isn't related to the API. I thought maybe something in the protocol may be out of sync. If that is impossible, let me know, and I will close.

Is this the only weapon's data error you found? I also hard-coded it, but I want my bot to learn battle outcomes based on these data, and that will be hard if there are errors.

**Comment by RaphaelRoyerRivard** [comment]
As far as I know it is the only one. But other units have abilities instead of attacks (like Disruptors, Banelings, Oracles) and also bunkers can attack without weapon info, so you can't only depend on that data.

**Comment by mboedigh** [comment]
I will use ability information too, but that will have to be learned separately, because there is no database available in the API afaik.

Is there any possibility that the reason BC weapons are empty (I think they were correct at some point in the past) is because the protocol is out of sync between the game and the api? 
If not, then I can close this issue.

**Comment by RaphaelRoyerRivard** [comment]
I don't know for how long this problem has been known, but it is pre-4.8.4. So it did not come along with the breaking changes. And I don't know why the weapons aren't there, we could check in the xml file with all unit information to see if it is there, but I forgot where that file was.

**Comment by mboedigh** [comment]
Thanks. I don't even know there was an xml, or where or how it gets produced and updated

**Comment by alkurbatov** [comment]
@mboedigh I think, it is possible to extend the API with proper weapon data. There are several problems with the data retrieved from the game (e.g. units cost, tech aliases). Unfortunately, I haven't deeply investigated it.
