### ISSUE TITLE
Allow to enable raw_affects_selection

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/cpp-sc2#29]
As it allows to significantly reduce apm. However, with this option human can't control units while bot playing. This could be not a huge issue, but seems that we should allow to disable the option.

**Comment by RaphaelRoyerRivard** [comment]
I coded it yesterday, but forgot to push so I can't submit a pull request atm. And since it can mess with the debugging process by selecting different units, I chose to set it to false in debug and true otherwise.

**Comment by alkurbatov** [comment]
Fixed in #38
