### ISSUE TITLE
Clean up UpdateObservation(...), UnitPool::CreateUnit() and related

### ISSUE THREAD

**Issue by mboedigh** [alkurbatov/cpp-sc2#32]
ObservationImp::UpdateObservation() is kind of messy. While tracking units, it does a fair amount of rework each game_loop and does not cleanly issue events. This has lead to several publicly reported bugs and weird behaviors with new and idled units. 
I have streamlined this process  in my own fork (diverged a while back). I believe it more cleanly and efficiently tracks events on units and also tracks units damaged each frame.  
Is this something that is of interest here? If so, how can I go about adding or discussing them.

**Comment by alkurbatov** [comment]
Hi @mboedigh 
Of course PRs are highly appreciated. Please, describe in more details what actually should be cleaned/improved.
As for new events, we have ongoing discussion here https://github.com/alkurbatov/cpp-sc2/issues/7.

Please, also take a look at https://github.com/alkurbatov/cpp-sc2/issues/9 before sending a PR.

**Comment by mboedigh** [comment]
I'll work on it, and send a PR.
