### ISSUE TITLE
define general_holdposition enum

### ISSUE THREAD

**Issue by mboedigh** [alkurbatov/cpp-sc2#34]
This may be a duplicate of fix holdposition, but I couldn't tell based on the description. 
Like MOVE, PATROL, HOLDPOSITION has a new enum that appears to be the generalization of specialized commands (If I understand correctly, which is questionable here). 
It looks like move and patrol enum values were _changed_, rather than adding new enums for the generalized values. I propose doing the same for HOLDPOSITION (change value from 18 to 3793)

**Comment by alkurbatov** [comment]
Yep, this is mostly the dup of 'fix holdposition'. 

A small portion of history :)
I thought about adding 'general' versions of the same commands as it allows to support older game versions. But so far it is unlikely that we can (should) support something older than 4.10.
From the other point of view, having both 'general' and 'basic' versions of the same command could be quite confusing for a developer.

**Comment by mboedigh** [comment]
so, if we want to learn from an old replay, will the commands be different?

**Comment by alkurbatov** [comment]
Actually, a good question. Yes, might be different if the replay game version < 4.10. 
It is a good idea to check the replays.

**Comment by mboedigh** [comment]
:) I can't get my replays working (issue #25), which is why I'm working on my scripted bot. If you can point me in the right direction for fixing 25 I would be glad to help. I'm just totally stumped by it.

**Comment by alkurbatov** [comment]
Will be fixed together with #43 in the next release.

**Comment by alkurbatov** [comment]
Fixed.
