### ISSUE TITLE
Functions, depend on SampleImageData don't work

### ISSUE THREAD

**Issue by KsanfFillum** [alkurbatov/cpp-sc2#4]
There are some calls that depend on `SampleImageData` function, for example `Observation()->IsPlacable` or `Obervation()->HasCreep`. All of them are throwing an assert here:
```
sc2_client::SampleImageData(const std::string& data, int width, int height, const Point2D& point, unsigned char& result):

assert(data.size() == width * height); (Line 439)
```

There is no difference on which frame or function you call this.

**Comment by alkurbatov** [comment]
Fixed in ba30bfaf.
