### ISSUE TITLE
Include weapon and armor upgrades in the Unit class

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [alkurbatov/cpp-sc2#54]
I believe they are in the protobuf, but not included in the Unit class of this API.

**Comment by alkurbatov** [comment]
Seems that we don't have it at hand:
https://github.com/Blizzard/s2client-proto/blob/24149a961632e659c89981ed6a879a4b0b86cdb9/s2clientprotocol/ui.proto#L26

**Comment by RaphaelRoyerRivard** [comment]
BuRny showed me this:
https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/raw.proto#L123-L125

**Comment by alkurbatov** [comment]
Ah, OK. It might work.

**Comment by alkurbatov** [comment]
Done.
