### ISSUE TITLE
Fix Duplicate OnDamageEvents

### ISSUE THREAD

**Issue by mboedigh** [alkurbatov/cpp-sc2#58]
If shields and health is damaged then two events are issued. 
I have a fix, but when i create a PR, GitHub shows many commits even though my log shows only one. The diff shown by GitHub is correct (one file with small number of lines changed)

My process was to 
git checkout dev
pull upstream dev # yours
git submodule update # not really needed this time
git commit 
git push
Next I tried to PR my dev branch from github

later I tried to create a PR from a new branch at the same ref as dev, but that didn't help. 
Any ideas why this happens or how to fix it so there is a single commit? I didn't need to push --force, which has been a culprit in the past.

**Comment by alkurbatov** [comment]
It looks ok. Perhaps you touched some commits during rebase before those actions?

I suggest to use a bit different workflow:
1. Create a separate branch cloned from `dev` (e.g. `my-dev`).
2. Sync the dev branch as usual.
3. `git checkout my-dev`.
4. Do `git rebase dev` in `my-dev`.

Imho, such approach works the best with the GitHub workflow.

**Comment by alkurbatov** [comment]
Fixed in #60.
